#toggles debug option.
debug:
  #hitbox
  hitbox: false
  #exception
  exception: false
  #pack
  pack: false
  #tracker
  tracker: false
#toggles indicator option.
indicator:
  #progress bar
  progress_bar: true
#toggle BetterModel's feature you want
module:
  #general entity model
  model: true
  #player model
  player-animation: true
#toggle resource pack generation
pack:
  #generates modern resource pack (>=1.21.4)
  generate-modern-model: true
  #generates legacy resource pack (<1.21.3)
  generate-legacy-model: true
#toggles metrics in bStats (https://bstats.org/plugin/bukkit/BetterModel/24237)
metrics: true
#enables sight-trace culling
sight-trace: true
#target item material about resource pack
item: leather_horse_armor
#max distance about sending an animation packet
max-sight: -1
#min distance about sending an animation packet
min-sight: 5
#resource pack namespace
namespace: "bettermodel"
#resource pack type (folder, zip)
pack-type: zip
#resoruce pack location
build-folder-location: BetterModel/build
#toggle following mob's invisibility
follow-mob-invisibility: true
#default frame time of animated texture
animated-texture-frame-time: 10
#toggles using Purpur afk (https://purpurmc.org/)
use-purpur-afk: true
#toggles version update announcement
version-check: true
#default mount controller (walk, fly)
default-mount-controller: walk
#keyframe insertion tick time
lerp-frame-time: 5
#toggles canceling player hotbar swap if target player is disguised or in player animation
cancel-player-model-inventory: false
#delay of applying hiding player entity
player-hide-delay: 3
#packet bundling size
packet-bundling-size: 16